### ISSUE TITLE
Github basics

### ISSUE THREAD

**Issue by TheMadHatter1316** [TheMadHatter1316/Treehouse#2]
learning how to use GitHub and all the features. this will be the base for me to build on.

##TODO
*Courses left to complete the Treehouse GitHub track*

* [ ] Hello, GitHub!
* [ ] Working by Yourself
* [ ] Working on a Team
* [ ] Create a Web Presence on GitHub!
* [ ] Get Involved in Open Source

🔢 👍 💯 🥇
